### ISSUE TITLE
#1 ToDo

### ISSUE THREAD

**Issue by TheLukaszNs** [TheLukaszNs/thelukaszns.github.io#1]
# Pierwsza oficjalna lista zadań.
- [ ] Poprawić wyświetlanie następujących elementów w niektórych przeglądarkach:
  - [ ] Rotacja,
  - [ ] Informacje o ciasteczkach,
  - [ ] Stopka,
  - [ ] Wyświetlanie przycisku Rozwinięcia i Schowania stopki.
- [X] Poprawić literówki (Jak na razie jest OK :smile:)
